/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;
import Main.MainForm;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import menu.dataCustomer;
import models.Customer;
import models.Pesanan;
import models.TabungGas;
/**
 *
 * @author ACER
 */
public class menuCustomer extends javax.swing.JFrame {
    static ArrayList<Customer> daftarCustomer = new ArrayList<>();
    static ArrayList<Pesanan> daftarPesanan = new ArrayList<>();
   
    /**
     * Creates new form menuCustomer
     */
    public menuCustomer() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnTambahCus = new javax.swing.JButton();
        btnLihatCus = new javax.swing.JButton();
        btnBuatPesan = new javax.swing.JButton();
        btnLihatPesan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENU CUSTOMER");

        btnTambahCus.setText("Tambah Customer");
        btnTambahCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahCusActionPerformed(evt);
            }
        });

        btnLihatCus.setText("Lihat Customer");
        btnLihatCus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatCusActionPerformed(evt);
            }
        });

        btnBuatPesan.setText("Buat Pesanan Gas");
        btnBuatPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuatPesanActionPerformed(evt);
            }
        });

        btnLihatPesan.setText("Lihat Pesanan Customer");
        btnLihatPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatPesanActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali ke Menu Utama");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(btnLihatCus)
                .addContainerGap(145, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuatPesan)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(149, 149, 149))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnTambahCus)
                            .addGap(137, 137, 137)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKembali)
                    .addComponent(btnLihatPesan))
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addComponent(btnTambahCus)
                .addGap(18, 18, 18)
                .addComponent(btnLihatCus)
                .addGap(18, 18, 18)
                .addComponent(btnBuatPesan)
                .addGap(18, 18, 18)
                .addComponent(btnLihatPesan)
                .addGap(18, 18, 18)
                .addComponent(btnKembali)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLihatCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatCusActionPerformed
            dataCustomer dataForm = new dataCustomer();
        
            StringBuilder sb = new StringBuilder();
            if (daftarCustomer.isEmpty()) {
                sb.append("Belum ada data customer.");
            } else {
                for (Customer c : daftarCustomer) {
                    sb.append("ID Customer: ").append(c.getId()).append("\n");
                    sb.append("Nama: ").append(c.getNama()).append("\n");
                    sb.append("Alamat: ").append(c.getAlamat()).append("\n\n");
                }
            }
            dataForm.setOutput(sb.toString());

            dataForm.setVisible(true);
            dispose();
    }//GEN-LAST:event_btnLihatCusActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new MainForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnTambahCusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahCusActionPerformed
        new formTambahCustomer().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTambahCusActionPerformed

    private void btnBuatPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuatPesanActionPerformed
        new formBuatPesanan().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnBuatPesanActionPerformed

    private void btnLihatPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatPesanActionPerformed
        dataCustomer pesananForm = new dataCustomer();

        // Buat isi daftar pesanan
        StringBuilder sb = new StringBuilder();
        if (daftarPesanan.isEmpty()) {
            sb.append("Belum ada pesanan.");
        } else {
            sb.append("=== DAFTAR PESANAN ===\n\n");
            for (Pesanan p : daftarPesanan) {
                sb.append("ID Customer : ").append(p.getIdCustomer()).append("\n");
                sb.append("Nama        : ").append(p.getNamaCustomer()).append("\n");
                sb.append("ID Tabung   : ").append(p.getIdTabung()).append("\n");
                sb.append("Jenis Gas   : ").append(p.getJenisTabung()).append("\n");
                sb.append("Jumlah      : ").append(p.getJumlahPesan()).append("\n\n");
            }
        }

        pesananForm.setOutput(sb.toString());
        pesananForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLihatPesanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuatPesan;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLihatCus;
    private javax.swing.JButton btnLihatPesan;
    private javax.swing.JButton btnTambahCus;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
