/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package menu;

import Main.MainForm;
import java.util.ArrayList;
import models.TabungGas;

/**
 *
 * @author ACER
 */
public class menuTabung extends javax.swing.JFrame {
    static ArrayList<TabungGas> daftarTabung = new ArrayList<>();

    static ArrayList<TabungGas> getDaftarTabung() {
        return daftarTabung;
    }

    /**
     * Creates new form menuTabung
     */
    public menuTabung() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLihatGas = new javax.swing.JButton();
        btnKelolaGas = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENU TABUNG GAS");

        btnLihatGas.setText("Lihat Tabung Gas");
        btnLihatGas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatGasActionPerformed(evt);
            }
        });

        btnKelolaGas.setText("Kelola Tabung Gas");
        btnKelolaGas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaGasActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLihatGas)
                    .addComponent(jLabel1))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKelolaGas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btnKembali)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(btnLihatGas)
                .addGap(18, 18, 18)
                .addComponent(btnKelolaGas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btnKembali)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLihatGasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatGasActionPerformed
        dataTabung TabungForm = new dataTabung();

        // Buat isi daftar pesanan
        StringBuilder sb = new StringBuilder();
        if (daftarTabung.isEmpty()) {
            sb.append("Belum ada Tabung Gas.");
        } else {
            sb.append("=== DAFTAR TABUNG GAS ===\n\n");
            for (TabungGas t : daftarTabung) {
                sb.append("ID: ").append(t.getId()).append("\n");
                sb.append("Jenis: ").append(t.getJenis()).append("\n");
                sb.append("Kapasitas: ").append(t.getKapasitas()).append("\n");
                sb.append("Jumlah Isi: ").append(t.getJumlahIsi()).append("\n");
                sb.append("ID Supplier: ").append(t.getIdSupplier()).append("\n");
                sb.append("Nama Supplier: ").append(t.getNamaSupplier()).append("\n");
                sb.append("Ketersediaan: ").append(t.isTersedia() ? "Tersedia" : "Habis").append("\n");
                sb.append("-----------------------------------\n");
            }
        }

        TabungForm.setOutput(sb.toString());
        TabungForm.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLihatGasActionPerformed

    private void btnKelolaGasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaGasActionPerformed
        new formKelolaTabung().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKelolaGasActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new MainForm().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuTabung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuTabung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuTabung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuTabung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuTabung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKelolaGas;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLihatGas;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
